#!/usr/bin/env python3
"""
GRBL Warp Transform Calibration Tool

This script helps calibrate the warp transform parameters by:
1. Testing known coordinates against the current transform
2. Providing easy adjustment of parameters
3. Generating test G-code for verification

Usage:
    python grbl/warp_calibration_tool.py
"""

import json
import os
from warp_transform import warp_transform_line, inverse


def load_warp_config():
    """Load current warp configuration"""
    config_path = "warp_config.json"
    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Config file not found: {config_path}")
        return None


def save_warp_config(config):
    """Save updated warp configuration"""
    config_path = "warp_config.json"
    with open(config_path, 'w') as f:
        json.dump(config, f, indent=2)
    print(f"Configuration saved to {config_path}")


def test_coordinates(test_points):
    """Test a set of coordinates through the current warp transform"""
    print("\n=== COORDINATE TRANSFORMATION TEST ===")
    print("Original -> Transformed")
    print("-" * 30)

    for point in test_points:
        original_x, original_y = point
        gcode_line = f"G01 X{original_x} Y{original_y}"
        transformed_line = warp_transform_line(gcode_line)
        print(f"({original_x:6.1f}, {original_y:6.1f}) -> {transformed_line}")


def generate_test_gcode(filename="test_warp_calibration.gcode"):
    """Generate a test G-code file with simple geometric patterns"""
    test_patterns = [
        # Simple square
        "G01 X10 Y10",
        "G01 X20 Y10",
        "G01 X20 Y20",
        "G01 X10 Y20",
        "G01 X10 Y10",

        # Diagonal lines
        "G01 X0 Y0",
        "G01 X30 Y30",
        "G01 X0 Y30",
        "G01 X30 Y0",

        # Circle approximation (8 points)
        "G01 X15 Y5",   # Bottom
        "G01 X22 Y8",   # Bottom-right
        "G01 X25 Y15",  # Right
        "G01 X22 Y22",  # Top-right
        "G01 X15 Y25",  # Top
        "G01 X8 Y22",   # Top-left
        "G01 X5 Y15",   # Left
        "G01 X8 Y8",    # Bottom-left
        "G01 X15 Y5",   # Back to bottom
    ]

    with open(filename, 'w') as f:
        f.write("; Test G-code for warp calibration\n")
        f.write("; Generated by warp_calibration_tool.py\n")
        f.write("G90 ; Absolute positioning\n")
        f.write("G01 F1000 ; Set feed rate\n")
        f.write("\n; Test patterns (original coordinates)\n")

        for line in test_patterns:
            f.write(line + "\n")

        f.write("\n; Same patterns with warp transform applied\n")
        for line in test_patterns:
            transformed = warp_transform_line(line)
            f.write(f"; {line} -> {transformed}\n")
            f.write(transformed + "\n")

    print(f"\nTest G-code saved to: {filename}")


def interactive_calibration():
    """Interactive calibration mode"""
    config = load_warp_config()
    if not config:
        print("Cannot load configuration file!")
        return

    print("=== INTERACTIVE WARP CALIBRATION ===")
    print("\nCurrent robot arm dimensions:")
    arm_dims = config["robot_arm_dimensions"]
    for key, value in arm_dims.items():
        print(f"  {key}: {value}")

    coord_sys = config["coordinate_system"]
    print(f"\nCurrent coordinate system:")
    print(f"  Origin offset: ({coord_sys['origin_offset_x']}, {coord_sys['origin_offset_y']})")
    print(f"  Scale factor: {coord_sys['scale_factor']}")

    print("\nOptions:")
    print("1. Test current configuration")
    print("2. Adjust scale factor")
    print("3. Adjust origin offset")
    print("4. Generate test G-code")
    print("5. Check GRBL $100/$101 settings")
    print("q. Quit")

    while True:
        choice = input("\nEnter choice: ").strip().lower()

        if choice == '1':
            test_points = [(10, 10), (20, 20), (30, 30), (0, 0), (40, 40)]
            test_coordinates(test_points)

        elif choice == '2':
            current = coord_sys['scale_factor']
            new_scale = input(f"Current scale factor: {current}. Enter new value: ")
            try:
                coord_sys['scale_factor'] = float(new_scale)
                save_warp_config(config)
                print(f"Scale factor updated to {new_scale}")
            except ValueError:
                print("Invalid number!")

        elif choice == '3':
            current_x = coord_sys['origin_offset_x']
            current_y = coord_sys['origin_offset_y']
            print(f"Current origin offset: ({current_x}, {current_y})")
            new_x = input("Enter new X offset: ")
            new_y = input("Enter new Y offset: ")
            try:
                coord_sys['origin_offset_x'] = float(new_x)
                coord_sys['origin_offset_y'] = float(new_y)
                save_warp_config(config)
                print(f"Origin offset updated to ({new_x}, {new_y})")
            except ValueError:
                print("Invalid numbers!")

        elif choice == '4':
            generate_test_gcode()

        elif choice == '5':
            print("\nGRBL Configuration Check:")
            print("Run these commands in your GRBL terminal:")
            print("  $100  (X-axis steps per mm)")
            print("  $101  (Y-axis steps per mm)")
            print("\nThe mathematician suggests reviewing these values")
            print("to correct the X/Y ratio if drawings are distorted.")

        elif choice == 'q':
            break

        else:
            print("Invalid choice!")


if __name__ == "__main__":
    print("GRBL Warp Transform Calibration Tool")
    print("=" * 40)

    # Quick status check
    config = load_warp_config()
    if config:
        print(f"\nLoaded configuration version {config.get('version', 'unknown')}")
        print(f"Current issues noted: {config['calibration_notes']['current_issues']}")

    # Run interactive calibration
    interactive_calibration()