#!/usr/bin/env python3
"""
Simple test of dramatic startle - just run machine.py and walk into view!
"""

print("🎯 DRAMATIC STARTLE TEST")
print("="*50)
print("The startle reaction is now MUCH more dramatic!")
print()
print("NEW FEATURES:")
print("Phase 1 (0-0.4s): SHOCK WAVE")
print("  - Massive shock forces (80x normal!)")
print("  - Chaotic shock noise (±60°)")
print("  - Like getting hit by lightning!")
print()
print("Phase 2 (0.4-1.2s): RAPID TREMBLING") 
print("  - Fast oscillation at 15Hz")
print("  - ±25° trembling around shock position")
print("  - Like hand is shaking from shock")
print()
print("🚀 TO TEST:")
print("1. Run: python machine.py --debug")
print("2. Walk into camera view")
print("3. Look for: '😲 STARTLE! Face detected'")
print("4. Watch for DRAMATIC finger movements!")
print()
print("If it still doesn't work, check:")
print("- Arduino Serial Monitor for commands")
print("- Physical servo connections")
print("- Servo power supply")
print()
print("The Python side is definitely working - it's either:")
print("- Arduino not receiving commands")
print("- Servos not physically connected")
print("- Not enough dramatic movement to notice")
print()
print("✨ This new version should be IMPOSSIBLE to miss!")
