MEANINGFUL_MOTIFS = {
    # People and human characteristics - HIGHEST PRIORITY
    "person",
    "man",
    "woman",
    "face",
    "eyes",
    "smile",
    "hair",
    "beard",
    "mustache",
    "glasses",
    "hands",
    "expression",
    "gesture",
    # Physical appearance descriptors
    "dark hair",
    "light hair",
    "brown hair",
    "black hair",
    "gray hair",
    "curly hair",
    "straight hair",
    "long hair",
    "short hair",
    "blue eyes",
    "brown eyes",
    "green eyes",
    "tall person",
    "short person",
    # Clothing that helps identify people
    "shirt",
    "sweater",
    "jacket",
    "dress",
    "suit",
    "tie",
    "hat",
    "cap",
    "scarf",
    "jewelry",
    "watch",
    "necklace",
    "earrings",
    # Visual objects that matter
    "camera",
    "phone",
    "computer",
    "laptop",
    "monitor",
    "screen",
    "desk",
    "table",
    "chair",
    "window",
    "door",
    "mirror",
    "artwork",
    "picture",
    "book",
    "paper",
    "notebook",
    "pen",
    "pencil",
    "brush",
    "lamp",
    "plant",
    "bottle",
    "glass",
    "cup",
    "clothes",
    "shirt",
    "glasses",
    "watch",
    "necklace",
    # Spaces and environments
    "kitchen",
    "bedroom",
    "office",
    "studio",
    "workspace",
    "bathroom",
    "garden",
    "restaurant",
    "cafe",
    "library",
    # Activities worth tracking
    "writing",
    "reading",
    "drawing",
    "painting",
    "cooking",
    "eating",
    "drinking",
    "typing",
    "working",
    "studying",
    "creating",
    "cleaning",
    # Creative/professional
    "artist",
    "writer",
    "programmer",
    "designer",
    "musician",
    "teacher",
    "student",
    "painting",
    "sketch",
    "drawing",
    "music",
    "violin",
    "piano",
    "guitar",
    "canvas",
    "easel",
    "palette",
    "instrument",
    # Specific environmental qualities
    "cluttered",
    "organized",
    "messy",
    "bright",
    "shadowy",
    "sunlit",
    "colorful",
    "vintage",
    "modern",
    "minimalist",
    # Natural elements
    "sunlight",
    "shadow",
    "reflection",
    "tree",
    "flowers",
    "water",
    "laundry",
}

MOTIF_BLACKLIST = {
    "thought",
    "about",
    "appears",
    "might",
    "there",
    "where",
    "their",
    "seems",
    "front",
    "right",
    "various",
    "perhaps",
    "notice",
    "important",
    "minute",
    "moment",
    "sense",
    "thoughts",
    "remember",
    "visible",
    "individual",
    "young",
    "short",
    "neutral",
    "natural",
    "quiet",
    "personal",
    "domestic",
    "indoor",
    "activity",
    "items",
    "object",
    "scene",
    "image",
    "quite",
    "really",
    "pretty",
    "little",
    "small",
    "large",
    "good",
    "nice",
    "simple",
    "basic",
    "special",
    "general",
    "normal",
    "usual",
    "common",
    "different",
    "similar",
    "other",
    "feeling",
    "looking",
    "getting",
    "making",
    "doing",
    "being",
    "having",
}


MEANINGFUL_CATEGORIES = {
    # Objects and tools
    "camera",
    "phone",
    "computer",
    "laptop",
    "monitor",
    "screen",
    "desk",
    "table",
    "chair",
    "window",
    "door",
    "mirror",
    "picture",
    "artwork",
    "book",
    "paper",
    "pen",
    "pencil",
    "lamp",
    "light",
    "plant",
    "flower",
    "bottle",
    "glass",
    "cup",
    "plate",
    "bowl",
    "clothes",
    "shirt",
    "jacket",
    "hat",
    "glasses",
    "watch",
    "necklace",
    "ring",
    # Places and environments
    "kitchen",
    "bedroom",
    "office",
    "studio",
    "workspace",
    "bathroom",
    "garden",
    "restaurant",
    "cafe",
    "library",
    "park",
    "street",
    "building",
    # Activities and skills
    "writing",
    "reading",
    "drawing",
    "painting",
    "cooking",
    "eating",
    "drinking",
    "typing",
    "working",
    "studying",
    "playing",
    "exercising",
    "sleeping",
    "talking",
    "listening",
    "watching",
    "thinking",
    "creating",
    "building",
    "cleaning",
    # Creative and professional terms
    "artist",
    "writer",
    "programmer",
    "designer",
    "musician",
    "teacher",
    "student",
    "painting",
    "sketch",
    "drawing",
    "music",
    "instrument",
    "violin",
    "piano",
    "guitar",
    "canvas",
    "brush",
    "pencil",
    "marker",
    "easel",
    "palette",
    # Specific descriptive qualities (not generic emotions)
    "cluttered",
    "organized",
    "messy",
    "clean",
    "bright",
    "shadowy",
    "sunlit",
    "colorful",
    "monochrome",
    "vintage",
    "modern",
    "rustic",
    "elegant",
    "minimalist",
    # Natural elements
    "sunlight",
    "shadow",
    "reflection",
    "tree",
    "leaves",
    "flowers",
    "water",
    "sky",
}

CONCRETE_NOUN_HINTS = {
    "desk",
    "chair",
    "table",
    "window",
    "door",
    "wall",
    "floor",
    "ceiling",
    "kitchen",
    "bedroom",
    "bathroom",
    "office",
    "studio",
    "workspace",
    "computer",
    "laptop",
    "phone",
    "camera",
    "monitor",
    "screen",
    "book",
    "paper",
    "pen",
    "pencil",
    "brush",
    "canvas",
    "easel",
    "plant",
    "flower",
    "tree",
    "sunlight",
    "shadow",
    "reflection",
}
